---
title: "chapter_3_book"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```

```{r} 
#dataframe
mpg <- ggplot2::mpg
nrow(mpg)
ncol(mpg)
dim(mpg)

#drv means the the type of drive train
#cyl is the number of cylinders
#hwy is the highway miles per gallos #cty is the city miles per gallon
```
```{r, fig.width = 1, fig.height = 1}
ggplot(mpg)

```

```{r, fig.width = 4, fig.height = 2}
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy))
  geom_point(aes(displ, hwy))
```


```{r, fig.width = 2, fig.height = 2}
ggplot(mpg) +
  geom_point(mapping = aes(hwy, cyl))
  geom_point(aes(hwy, cyl))
```

```{r, fig.width = 3, fig.height = 1.5}
ggplot(mpg) +
  geom_point(mapping = aes(class, drv))
  geom_point(aes(class, drv))
```

```{r, fig.width = 4, fig.height = 2}
#uses colors to distinguish discrete variable -> class 
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = class))
  geom_point(aes(displ, hwy, color = class))
#uses size to distinguish discrete variable -> class 
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = class))
  geom_point(aes(displ, hwy, size = class))
#uses alpha (aesthetic) to distinguish discrete variable -> class 
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, alpha = class))
  geom_point(aes(displ, hwy, alpha = class))
#uses shape (aesthetic) to distinguish discrete variable -> class  #ggplot can only use 6 shapes at a time
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, shape = class))
  geom_point(aes(displ, hwy, shape = class))
#example how not to define a specific colour for the discrete variable color
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = "blue"))
  geom_point(aes(displ, hwy, color = "blue"))
#how to use a specific colors to distinguish discrete variable -> class 
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy), color = "blue")
  geom_point(aes(displ, hwy), color = "blue")
```


```{r, fig.width = 3, fig.height = 1.5}
#3.3.1.1 see answer in chunk above
#3.3.1.2 
# categorical: model,manufacturer,Trans, drv,fl,class
# continuous: displ, year, cyl, cty, hwy
#3.3.1.3
#continous
#cyl
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = cyl))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = cyl))
#a continous variable cannot be mapped to a schape
#ggplot(mpg) +
  #geom_point(mapping = aes(displ, hwy, shape = cyl))
#cty
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = cty))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = cty))
#year
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = year))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = year))
#combining aes 
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = year, size = year))



```


```{r, fig.width = 3, fig.height = 1.5}
#Discrete/categorical
#model
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = model))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = model))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, shape = model))
#trans
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = trans))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = trans))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, shape = trans))
#drv
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = drv))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, size = drv))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, shape = drv))

# combining aes
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = drv, shape = drv))
ggplot(mpg) +
  geom_point(mapping = aes(displ, hwy, color = cyl, alpha = cyl))

```

```{r}
ggplot(mpg) + 
  geom_point(mapping = aes(displ, hwy, stroke = displ))

?geom_point
#stroke uses different sizes of dots for the categories of the data point

#Sizes defines the size and stroke and allows them to be used by referring to sizes
sizes <- expand.grid(size = (0:3) * 2, stroke = (0:3) * 2)

ggplot(sizes, aes(size, stroke, size = size, stroke = stroke)) + 
  geom_abline(slope = -1, intercept = 6, colour = "white", size = 6) + 
  geom_point(shape = 21, fill = "red") +
  scale_size_identity()


ggplot(mpg) +
  geom_point(aes(displ, hwy, colour = displ < 5))

#ggplot(mpg) +
  #geom_point(aes(displ, hwy), colour = displ < 5)
#colour needs to be inside the aes

ggplot(mpg) +
  geom_point(aes(displ, hwy, colour = displ < 5), stroke = 5)
#stroke can be placed outside aes

```
```{r} 
#3.5 facets examples
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
#facetwrap variable should be a discrete variable
#below code for facetwrap of 2 variables
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
#facet wrap for 3 variables
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl ~ class)
#facets in one dimension
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  facet_grid(. ~ class)




```

```{r}
#exercises 3.5.1.1
#facet wrap on a continous variable
#ggplot(mpg) + 
  #geom_point(aes(x = displ, y = hwy)) + 
  #facet_wrap(~ yeaar, nrow = 2)
#answer 3.5.1: leads to an error

#ex 3.5.1.
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
#versus
ggplot(mpg) + 
  geom_point(aes(x = drv, y = cyl))

#the facetted plot shows also the amount of data points, the non-facetted one shows only presence in a category. the empty cells mean that there is no data fore/the combination of variables does not exist

#3.5.1.3
ggplot( mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot( mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)

#these plots show how to whether to plot the rows or the columns in you facet


#3.5.1.4
ggplot( mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
#Orientation: row ~ col
#facets can be used to isolates groups of interest, easy visualize 

#3.5.1.5
ggplot( mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 1)
ggplot( mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, ncol = 1)

#using ncol and nrow you can determine the dimensions of the facet 
#facet_wrap wraps a 1d panel in to a 2d panel and used ncol and nrow, so you can customize
#facet_grid forms a matrix of panels 


```


```{r}
#3.6 examples
#scatter using geom_point
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy))

#line plot using geom_smooth
ggplot(mpg) + 
  geom_smooth(aes(x = displ, y = hwy))
#line plot with different linetypes
ggplot(mpg) + 
  geom_smooth(aes(x = displ, y = hwy, linetype = drv))

ggplot(mpg) +
  geom_smooth(aes(x = displ, y = hwy))
#plots the groups of drv within x and y             
ggplot(mpg) +
  geom_smooth(aes(x = displ, y = hwy, group = drv))
#colors different lines    
ggplot(mpg) +
  geom_smooth(
    aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

#plotting both scatter and lines in one figure
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

#simpifies the code above
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()
#different settings can be used for the type of plotting with plotting the data only once
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()

ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

#writing the plot this way allows for customizable settings for each layer

```
```{r}
#exercises 3.6
#3.6.1.1
#lineplot
ggplot(mpg) + 
  geom_smooth(aes(displ, hwy))
#or
ggplot(mpg) + 
  geom_line(aes(displ, hwy))
#boxplot
ggplot(mpg) + 
  geom_boxplot(aes(displ, hwy))
#histogram
ggplot(mpg,aes(displ)) + 
  geom_histogram()
#playing around
ggplot(mpg) + 
  geom_histogram(aes(displ)) +
  geom_histogram(aes(hwy)) +
  facet_grid(~ hwy)
ggplot(mpg) + 
  geom_histogram(aes(displ)) +
  geom_histogram(aes(hwy)) +
  facet_grid(~ class)
ggplot(mpg) + 
  geom_histogram(aes(displ)) +
  geom_histogram(aes(hwy)) +
  facet_wrap(~ class, ncol = 4)
#areachart
ggplot(mpg, aes(displ, hwy)) + 
  geom_area()
#or geom ribbon
ggplot(mpg, aes(displ, hwy, ymin=0 , ymax=50)) + 
  geom_ribbon()
#for ribbon to look good I probably need to write dat/level to plot

#3.6.1.2
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
#predicted the outcome
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) + 
  geom_point(show.legend = FALSE) + 
  geom_smooth(show.legend = FALSE)
#3.6.1.3. show legend is false removes the legend/does not show the legend
#3.6.1.4.the se argument shows the standard error

#3.6.1.5
#they won't look different, below is jsut 2 diff. ways of plotting the same
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))

```

```{r}
#3.6.1.6
#plot 1
ggplot(mpg, aes(displ,hwy)) + 
  geom_point(stroke = 3.5, show.legend = FALSE) + 
  geom_smooth(se = FALSE, show.legend = FALSE)
#plot 2
ggplot(mpg, aes(displ,hwy, line = drv)) + 
  geom_point(stroke = 3.5, show.legend = FALSE) + 
  geom_smooth(se = FALSE, show.legend = FALSE)
#plot 3
ggplot(mpg, aes(displ,hwy, color = drv)) + 
  geom_point(stroke = 3.5) + 
  geom_smooth(se = FALSE)
#plot 4
ggplot(mpg, aes(displ,hwy)) + 
  geom_point(aes(color = drv), stroke = 3.5) + 
  geom_smooth(se = FALSE)
#plot 5
ggplot(mpg, aes(displ,hwy, linetype= drv)) + 
  geom_point(aes(color = drv), stroke = 3.5) + 
  geom_smooth(se = FALSE)
#plot 6
ggplot(mpg, aes(displ,hwy, fill = drv)) + 
  geom_point(color = "white", size = 3.5, stroke = 3.5)

ggplot(mpg, aes(displ,hwy, fill = drv)) + 
  geom_point(shape  = 21, color = "white", size = 3.5, stroke = 3.5)
#without defining shapes drv does not get coloured.

```
```{r}
#3.7 examples
diamonds <- ggplot2::diamonds

ggplot(diamonds) +
  geom_bar(mapping = aes(x = cut))

ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))
```
```{r, fig.height= 1,fig.width=2}
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(demo) +
  geom_bar(mapping = aes(cut, freq), stat = "identity")

ggplot(diamonds) + 
  geom_bar(mapping = aes(cut, stat(prop), group = 1))

ggplot(diamonds) + 
  stat_summary(
    mapping = aes(cut, depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )

```
```{r}
#exercises 3.7

#3.7.1.1
?stat_summary
#pointrange is the default geom
#rewrite
ggplot(diamonds, aes(cut, depth)) + 
  geom_pointrange(aes(ymin = depth, ymax = depth))

#3.7.1.2
#geom_col
ggplot(diamonds, aes(cut, depth)) + 
  geom_col()
#there are no differences

ggplot(diamonds, aes(cut, depth)) + 
  stat_smooth(aes(depth, ymin = depth, ymax = depth))
#stat_smooth is controlled bij x or y, and x/y min and max

#3.7.1.5
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = after_stat(prop)))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = color, y = after_stat(prop)))

```

```{r}
#Examples 3.8
ggplot(diamonds) + 
  geom_bar(aes(x = cut, colour = cut))
ggplot(diamonds) + 
  geom_bar(aes(x = cut, fill = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))
#identity allows for overlapping in the case of bar graphs
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")
#sets bar to the same height, comparisons for proportions
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
#dodge places overlapping objects beside one another
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
#Jitter prevents overplotting of scatterpoints
ggplot(mpg) + 
  geom_point(aes(displ, hwy), position = "jitter")
```

```{r}
#Exercises 3.8
#3.8.1.1
ggplot(mpg, aes(cty, hwy)) + 
  geom_point(position = "jitter")

ggplot(mpg, aes(cty, hwy)) + 
  geom_point(aes(colour = class), position = "jitter")
#3.8.1.2.
#alpha/colour/fill/group/shape/size/stroke are the parameters of jitter and x (or) y
#3.8.1.3
ggplot(mpg, aes(cty, hwy)) + 
  geom_count(position = "jitter")
ggplot(mpg, aes(cty, hwy)) + 
  geom_count(aes(colour = class), position = "jitter")
#3.8.1.4
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot()
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot(position = "dodge")
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot(position = "identity")
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot()
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot(position = "dodge")
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot(position = "identity")
#no position adjusment or is it dodge

```


```{r}
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot(aes(group = class))
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot(aes(group = class), position = "dodge")
ggplot(mpg, aes(cty, hwy))+
  geom_boxplot(aes(group = class), position = "identity")
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot(aes(group = class))
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot(aes(group = class), position = "dodge")
ggplot(mpg, aes(displ, hwy))+
  geom_boxplot(aes(group = class), position = "identity")
```



```{r}
#Examples 3.9
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()
```

```{r}
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()

```


```{r}
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()

```


```{r}
#3.9.1.1
bar2 <- ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = color, y = after_stat(prop)))

bar2 + coord_flip()
bar2 + coord_polar()

#3.9.1.2
#labs() makes labels for graphs/figures

#3.9.1.3
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()
ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_map()
# the difference is the size of the image/the grid in the background

#3.9.1.4
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + 
  geom_abline() +
  coord_fixed()
#without coord_fixed it does not run, coord_fixed is responsible for a fixed scale.
#that it is linear correlated
#geom_abline adds definitions (rules) to the plot

```





