---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
#filter
#arrange
#select
#mutate
#summarise
library(tidyverse)
library(magrittr)
library(ggblanket)
library(readxl)

left_output <- read_excel("21-10-26_09_left_output.xlsx")
df <- read.table("lisadatacombined-RCLUB.txt",sep="\t",header=T)
head(df)
```

```{r}
#pet.angle over image
ggplot(df) +
  geom_line(aes(image,pet.angle,colour=plant))
#leaf.angle over image
ggplot(df) +
  geom_line(aes(image,leaf.angle,colour=plant))
#leaf.angle gives a smoother line


```



#modifications
```{r}
calc <- select(df, pixlen, pet.len, plant, image) %>%
  mutate(petinmm = 10*pet.len/pixlen)

#pet.angle over image
ggplot(calc) +
  geom_line(aes(image,petinmm,colour=plant))
ggplot(calc) +
  geom_smooth(aes(image,petinmm,colour=plant))
```



```{r}
head(df)
dfmm <- df %>%
  select(image, pet.len:plant) %>%
  mutate(petinmm = 10*pet.len/pixlen, leafleninmm = 10*leaf.len/pixlen, laminmm = 10*lamina.len/pixlen) 

#plots
ggplot(dfmm) +
  geom_line(aes(image,petinmm,colour=plant))
ggplot(dfmm) +
  geom_line(aes(image,leafleninmm,colour=plant))
ggplot(dfmm) +
  geom_line(aes(image,laminmm,colour=plant))


ggplot(dfmm) +
  geom_line(aes(image,petinmm,colour=plant))+
  geom_smooth(aes(image,petinmm,colour=plant))
ggplot(dfmm) +
  geom_line(aes(image,leafleninmm,colour=plant))+
   geom_smooth(aes(image,leafleninmm,colour=plant))
ggplot(dfmm) +
  geom_line(aes(image,laminmm,colour=plant))+
  geom_smooth(aes(image,laminmm,colour=plant))

```
#MEAN pet.angle
```{r}
by_image <- group_by(dfmm, image, plant, pet.angle)
summarise(by_image, mean.angle = mean(pet.angle, na.rm = TRUE))

by_plant <- group_by(dfmm, plant, pet.angle)
summarise(by_plant, mean.angle = mean(pet.angle, na.rm = TRUE))

```

#baslines
```{r}
head(dfmm)
means <- select(dfmm, -(image), -(pixlen:plant)) %>%
  summarise(mean.pet.len = mean(petinmm), mean.pet.angle = mean(pet.angle), mean.leaf.len = mean(leafleninmm), mean.leaf.angle = mean(leaf.angle), mean.lam.len = mean(laminmm), mean.lam.angle = mean(lamina.angle))  

dfmm
means

baseline <- select(dfmm, -(image), -(pixlen:plant)) %>%
  slice(1:5) %>%
  summarise(bl.pet.len = mean(petinmm), bl.pet.angle = mean(pet.angle), bl.leaf.len = mean(leafleninmm), bl.leaf.angle = mean(leaf.angle), bl.lam.len = mean(laminmm), bl.lam.angle = mean(lamina.angle)) 

baseline

```

```{r}

cor_bl <- dfmm %>%
  mutate(cor.pet.len = petinmm - baseline[1,"bl.pet.len"],
         cor.pet.angle = pet.angle - baseline[1,"bl.pet.angle"],
         cor.leaf.len = leafleninmm - baseline[1,"bl.leaf.len"],
         cor.leaf.angle = leaf.angle - baseline[1,"bl.leaf.angle"],
         cor.lamina.len = laminmm - baseline[1,"bl.lam.len"],
         cor.lamina.angle = lamina.angle - baseline[1,"bl.lam.angle"])
cor_bl


ggplot(cor_bl) +
  geom_line(aes(image,leaf.angle),colour="green") +
  geom_line(aes(image,cor.leaf.angle),colour="light green")

ggplot(cor_bl) +
  geom_smooth(aes(image,leaf.angle),colour="green") +
  geom_smooth(aes(image,cor.leaf.angle),colour="light green")

ggplot(cor_bl) +
  geom_line(aes(image,pet.angle),colour="green") +
  geom_line(aes(image,cor.leaf.angle),colour="light green")

ggplot(cor_bl) +
  geom_smooth(aes(image,pet.angle),colour="green") +
  geom_smooth(aes(image,cor.pet.angle),colour="light green")

ggplot(cor_bl) +
  geom_line(aes(image,pet.angle),colour="green") +
  geom_line(aes(image,cor.leaf.angle),colour="light green")

ggplot(cor_bl) +
  geom_smooth(aes(image,lamina.angle),colour="green") +
  geom_smooth(aes(image,cor.lamina.angle),colour="light green")

```

#image to time of day
```{r}
time <- cor_bl %>%
  mutate(hours = (image+600)%/%60, mins =(image+600)%%60)

time %<>% 
  mutate(hh.mm = paste(hours, mins, sep ="."))
 

ggplot(time) +
 geom_point(aes(hh.mm, cor.pet.len))
  
ggplot(time)+
  geom_line(aes(hh.mm, cor.pet.len))

ggplot(time)+
  geom_line(aes(hh.mm, cor.pet.len))


```

